name: Sync API Spec

on:
  repository_dispatch:
    types: [api_spec_updated]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Node (Bun)
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.2.17'

      - name: Fetch OpenAPI spec from source repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo=${{ github.event.client_payload.spec_repo }}
          path=${{ github.event.client_payload.spec_path }}
          curl -sSL -H "Authorization: token ${GH_TOKEN}" \
            -H "Accept: application/vnd.github.raw+json" \
            https://api.github.com/repos/${repo}/contents/${path} > openapi.json
          jq . openapi.json > /dev/null

      - name: Update working tree with new spec
        run: |
          mkdir -p src
          mv openapi.json src/openapi.json

      - name: Install deps
        run: bun install --frozen-lockfile || bun install

      - name: Build
        run: bun run build

      - name: Test
        run: bun test

      - name: Commit and push to main
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          if git diff --quiet --exit-code src/openapi.json; then
            echo "No changes to spec; skipping commit."
            exit 0
          fi
          git add src/openapi.json
          git commit -m "chore: sync API spec from ${{ github.event.client_payload.spec_repo }}@${{ github.event.client_payload.spec_sha }}"
          git push origin HEAD:main
